frr defaults traditional
hostname r1
!
interface eth0
 ip address 10.204.1.1/24
!
interface eth1
 ip address 10.204.0.1/24
!
router bgp 64601
 bgp router-id 10.204.0.1
 no bgp ebgp-requires-policy
 neighbor 10.204.0.2 remote-as 64602
 address-family ipv4 unicast
  network 10.204.1.0/24
 exit-address-family
!
