frr defaults traditional
hostname r2
!
interface eth0
 ip address 10.204.2.1/24
!
interface eth1
 ip address 10.204.0.2/24
!
router bgp 64602
 bgp router-id 10.204.0.2
 no bgp ebgp-requires-policy
 neighbor 10.204.0.1 remote-as 64601
 neighbor 10.204.0.1 timers 5 15
 address-family ipv4 unicast
  network 10.204.2.0/24
 exit-address-family
!
