frr defaults traditional
hostname r2
!
interface eth0
 ip address 10.203.12.2/24
 ip ospf area 0
!
interface eth1
 ip address 10.203.23.2/24
 ip ospf area 0
!
router ospf
 ospf router-id 10.203.0.2
!
