frr defaults traditional
hostname r3
!
interface eth0
 ip address 10.203.23.3/24
 ip ospf area 0
 ip ospf network point-to-point
!
interface eth1
 ip address 10.203.3.1/24
 ip ospf area 0
!
router ospf
 ospf router-id 10.203.0.3
 passive-interface eth1
!
